### ISSUE TITLE
Duplicate declaration

### ISSUE THREAD

**Issue by dashaluna** [Chassis/phpcs#9]
Error: Duplicate declaration: Package[php7.0-dev] is already declared in file /vagrant/extensions/phpcs/modules/phpcs/manifests/init.pp:24; cannot redeclare at /vagrant/extensions/composer/modules/composer/manifests/init.pp:13 on node xxx.local

**Comment by BronsonQuick** [comment]
🤔 Looks like you hit this issue which we've fixed: https://github.com/Chassis/phpcs/issues/8 You should be able to fix it by updating the Composer submodule `cd extensions/composer; git checkout master; git pull; vagrant provision;`

I'll close this issue for now but feel free to open it if that doesn't fix it. Thanks!
